CREATE DATABASE IF NOT EXISTS musicbox CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE musicbox;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(190) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  avatar_path VARCHAR(255) DEFAULT NULL,
  reset_code VARCHAR(10) DEFAULT NULL,
  reset_expires DATETIME DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS user_rewards (
  user_id INT PRIMARY KEY,
  points INT NOT NULL DEFAULT 0,
  best_score INT NOT NULL DEFAULT 0,
  current_streak INT NOT NULL DEFAULT 0,
  surprise_unlocked TINYINT(1) NOT NULL DEFAULT 0,
  CONSTRAINT fk_rewards_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS songs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(140) NOT NULL,
  artist VARCHAR(140) NOT NULL,
  genre VARCHAR(60) NOT NULL,
  year INT NOT NULL,
  duration VARCHAR(10) NOT NULL,
  cover TEXT NOT NULL,
  audio_url TEXT NOT NULL,
  featured TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
